CREATE TABLE options (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    survey_id INT NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);